# -*- coding: utf-8 -*-
"""V2Sign_Language_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OOGNzddDpvl5jFMpeECvHqvVQPd6Ni0
"""

!pip install pandas numpy scikit-learn tensorflow matplotlib

from google.colab import files
uploaded = files.upload()

!ls -lh

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Load CSV, specifying no header and then renaming the first column to 'label'
df = pd.read_csv("asl_handmarks.csv", header=None)
df.rename(columns={0: 'label'}, inplace=True)

# Separate labels and features
X = df.drop("label", axis=1).values
y_text = df["label"].values

# Encode letter labels into numbers
le = LabelEncoder()
y = le.fit_transform(y_text)

num_classes = len(le.classes_)

print("Labels:", le.classes_)
print("Samples:", X.shape)

import tensorflow as tf
from tensorflow.keras import layers, models

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Build a tiny neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(63,)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.Dense(num_classes, activation="softmax")
])



model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train model
history = model.fit(X_train, y_train, epochs=30, validation_data=(X_test, y_test))

# Evaluate
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc:.3f}")

import matplotlib.pyplot as plt

# Plot training & validation accuracy
plt.figure(figsize=(8,6))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# Plot training & validation loss
plt.figure(figsize=(8,6))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Model Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

import numpy as np
import tensorflow as tf

# ------------------------------
# 1. Save label classes from existing LabelEncoder
# ------------------------------
np.save("label_classes.npy", le.classes_)
print("Saved label_classes.npy")

# ------------------------------
# 2. Convert Keras model → TFLite
# ------------------------------
converter = tf.lite.TFLiteConverter.from_keras_model(model)

# Use only builtin TFLite ops (safer for Pi runtime)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]

# (Optional) don’t use optimizations for now
# converter.optimizations = []

tflite_model = converter.convert()

# ------------------------------
# 3. Save TFLite model
# ------------------------------
with open("asl_landmarks.tflite", "wb") as f:
    f.write(tflite_model)

print("🎉 Exported TFLite model and label files!")

files.download("asl_landmarks.tflite")
files.download("label_classes.npy")

import tensorflow as tf

# Load your TFLite model
interpreter = tf.lite.Interpreter(model_path="asl_landmarks.tflite")
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print("INPUT DETAILS:")
print(input_details)

print("\nOUTPUT DETAILS:")
print(output_details)